version: "1"

services:
  postgres:
    image: postgres
    container_name: total-energies-giza-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db-total-energies-giza
    volumes:
      - data_postgres:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: total-energies-giza-redis
    ports:
      - "6379:6379"
    volumes:
      - data_redis:/data

volumes:
  data_postgres:
  data_redis:
